---
- hosts: ec2-52-87-112-253.compute-1.amazonaws.com
  # roles:
  #   - mapd-ansible
  sudo: yes
  tasks:
  # - name: Update and upgrade apt packages
  #   become: true
  #   apt:
  #     upgrade: yes
  #     update_cache: yes
  #     cache_valid_time: 86400 #One day

  # - name: Install apt-transport-https
  #   become: true
  #   apt:
  #     name: apt-transport-https
  #     state: latest

  # - name: Group MapD
  #   group:
  #     name: mapd
  #     state: present

  # - name: Create a MapD user
  #   user:
  #     name: mapd
  #     groups:
  #      - mapd
  #     state: present
  #     shell: /bin/bash       # Defaults to /bin/bash
  #     system: no             # Defaults to no
  #     createhome: yes        # Defaults to yes
  #     home: /home/mapd  # Defaults to /home/<username>

  # # - name: Enable ufw
  # #   ufw: state=disabled policy=allow

  # # - name: Enable ufw
  # #   ufw: state=enabled policy=allow

  # - name: Open Immerse Port 9092
  #   ufw: rule=allow port=9092 proto=tcp

  # - name: Allow ssh in
  #   ufw: rule=limit name=OpenSSH

  # - name: CUDA | Install downloaded deb package for Ubuntu 16.04
  #   apt:
  #     deb: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.0.130-1_amd64.deb

  # - name: Install list of packages
  #   apt: name={{item}} state=installed
  #   with_items:
  #      - cuda-drivers
  #      - linux-image-extra-virtual
  #      - curl

  # - name: Get List File
  #   apt_repository:
  #     repo: deb https://releases.mapd.com/ce/apt/ stable cuda
  #     state: present
  #     filename: mapd     
  
  # - name: Add an Apt signing key
  #   shell: 'curl https://releases.mapd.com/GPG-KEY-mapd | sudo apt-key add -'

  # - name: Install mapd
  #   become: true
  #   apt:
  #     update_cache: yes
  #     name: mapd
  #     state: latest

  # - name: Create MapD Storage Directory
  #   file: 
  #     path: $MAPD_STORAGE
  #     state: directory
  #     owner: mapd

  # - name: Transfer the script
  #   copy: 
  #     src: mapd-ansible/files/install_mapd_systemd.new.sh
  #     dest: $MAPD_PATH/systemd 
  #     mode: 0777

  # - name: Execute the script
  #   script: mapd-ansible/files/install_mapd_systemd.new.sh

  - name: Make sure a Mapd Servers are running
    systemd: name={{item}} 
    state: started
    enabled: yes
    with_items:
       - mapd_server
       - mapd_web_server