---
  - name: populate /etc/environment
    lineinfile:
      dest: "/etc/environment"
      state: present
      regexp: "^{{ item.key }}"
      line: "{{ item.key }}={{ item.value}}"
    with_items: "{{ os_environment }}"

  - name: Group MapD
    become: true
    group:
      name: mapd
      state: present

  - name: Create a MapD user
    become: true
    user:
      name: mapd
      groups:
       - mapd
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      system: no             # Defaults to no
      createhome: yes        # Defaults to yes
      home: /home/mapd  # Defaults to /home/<username>

  - name: Create MapD Storage Directory
    become: true
    file: 
      path: $MAPD_STORAGE
      state: directory
      owner: mapd
  
  - include_tasks: ubuntu.yml
    when: ansible_os_family == "Debian"

  - include_tasks: redhat.yml
    when: ansible_os_family == "RedHat"

  - name: Transfer the script
    copy: 
      src: mapd-ansible/files/install_mapd_systemd.new.sh
      dest: $MAPD_PATH/systemd 
      mode: 0777

  - name: Execute the script
    become: true
    script: mapd-ansible/files/install_mapd_systemd.new.sh

  # Need to make this work to support internal initilization script performance
  # - name: Execute Script
  #   expect:
  #     script: $MAPD_PATH/systemd/install_mapd_systemd.sh
  #     responses:
  #       - echo

  - name: Make sure a Mapd Servers are running
    systemd: name={{item}} 
    state: started
    enabled: yes
    with_items:
       - mapd_server
       - mapd_web_server
